### ISSUE TITLE
0.3.0 баг

### ISSUE THREAD

**Issue by Player812185** [fmp-na/cassy-miner#3]
Оптимизации интерфейса для разных разрешений нет.

Версия 0.3.0
![Screenshot_2023-06-19-21-14-50-145_com FMPNA CassyMiner](https://github.com/fmp-na/cassy-miner/assets/130848925/78e75ebd-c93a-4d73-be73-1682774ffdfd)
![Screenshot_2023-06-19-21-10-04-685_com FMPNA CassyMiner](https://github.com/fmp-na/cassy-miner/assets/130848925/dc5aed72-2aba-4f2f-a7b3-9b4bdbe340ef)

**Comment by fb24m** [comment]
Ошибка будет исправлена в версии 0.0.4
