### ISSUE TITLE
0.3.0 баг #3

### ISSUE THREAD

**Issue by Player812185** [fmp-na/cassy-miner#5]
У угля иногда пропадает надпись
Как должно быть: Уголь (+1)
Как оно есть: (+1)

Версия 0.3.0
![IMG_20230619_212258](https://github.com/fmp-na/cassy-miner/assets/130848925/0db3b8ea-b272-490f-ad2a-093405ef36e5)

**Comment by fb24m** [comment]
Ошибка связана с тем, что иногда вместо угольного угля используется обычный уголь. Она будет исправлена в версии 0.0.4
